### ISSUE TITLE
build: create env variable for session token

### ISSUE THREAD

**Issue by S-ecki** [S-ecki/AdventOfCode-Starter-Dart#8]
- [ ] env variable for session
- [x] documentation for session token retrieval

**Comment by dumazy** [comment]
Have you thought about how to handle this? I'm kinda waiting to push my solutions until I can easily avoid my session token from being committed 😅 

- global env var
- gitignored file containing it
- ...

Since there's already some code generation going on, it might be nice to have an `init.dart` or something that could ask for the token and then generate a gitignored file containing this. Willing to help with this

**Comment by S-ecki** [comment]
Something like this is definitely needed!
Honestly, I would be happy with both solutions. The latter might be the nicest from a user perspective, as it would be tightly integrated with the general setup and the least effort from the user.

Super grateful for any contribution though! The feature is really needed, just didnt have time to address it yet.
